#
import turtle
turtle.speed(0)

#
def circ1():
    turtle.pensize(2)
    turtle.pu()
    turtle.goto(0, -235)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(95)
    turtle.end_fill()
    turtle.pu()
    turtle.goto(0, -235)
    turtle.pd()
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(48)
    turtle.end_fill()

def cua():
    turtle.pencolor("black")
    turtle.pensize(2)
    turtle.pu()
    turtle.goto(-110, 125)
    turtle.pd()
    turtle.forward(220)
    turtle.rt(90)
    turtle.forward(210)
    turtle.rt(90)
    turtle.forward(220)
    turtle.rt(90)
    turtle.forward(210)
    turtle.rt(90)

def lines():
    turtle.pensize(2)
    turtle.pu()
    turtle.goto(-110, 20)
    turtle.pd()
    turtle.goto(110, 20)
    turtle.goto(0, 230)
    turtle.goto(-110, 20)
    #
    turtle.pu()
    turtle.goto(-110, -85)
    turtle.pd()
    turtle.goto(0, 105)
    turtle.goto(110, -85)
    #
    turtle.pu()
    turtle.goto(-110, 125)
    turtle.pd()
    turtle.goto(0, 230)
    turtle.goto(110, 125)
    #
    turtle.pu()
    turtle.goto(-110, 125)
    turtle.pd()
    turtle.goto(0, -105)
    turtle.goto(110, 125)
    #
    turtle.pu()
    turtle.goto(-110, -85)
    turtle.pd()
    turtle.goto(0, -190)
    turtle.goto(110, -85)

def circ2():
    turtle.pencolor("black")
    #
    turtle.pensize(2)
    turtle.pu()
    turtle.goto(-30, -125)
    turtle.pd()
    turtle.circle(95)
    #
    turtle.pensize(2)
    turtle.pu()
    turtle.goto(30, -125)
    turtle.pd()
    turtle.circle(95)

def circ3():
    #1
    turtle.pensize(2)
    turtle.pu()
    turtle.goto(0, 210)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(20)
    turtle.end_fill()
    turtle.pu()
    turtle.goto(0, 240)
    turtle.pd()
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(15)
    turtle.end_fill()
    #2
    turtle.pu()
    turtle.goto(110, 105)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(20)
    turtle.end_fill()
    turtle.pu()
    turtle.goto(125, 125)
    turtle.pd()
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(15)
    turtle.end_fill()
    #3
    turtle.pu()
    turtle.goto(110, 0)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(20)
    turtle.end_fill()
    turtle.pu()
    turtle.goto(125, 5)
    turtle.pd()
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(15)
    turtle.end_fill()
    #4
    turtle.pu()
    turtle.goto(110, -105)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(20)
    turtle.end_fill()
    turtle.pu()
    turtle.goto(120, -110)
    turtle.pd()
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(15)
    turtle.end_fill()
    #5
    turtle.pu()
    turtle.goto(0, -210)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(20)
    turtle.end_fill()
    turtle.pu()
    turtle.goto(0, -210)
    turtle.pd()
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(15)
    turtle.end_fill()
    #6
    turtle.pu()
    turtle.goto(-110, -105)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(20)
    turtle.end_fill()
    turtle.pu()
    turtle.goto(-120, -110)
    turtle.pd()
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(15)
    turtle.end_fill()
    #7
    turtle.pu()
    turtle.goto(-110, 0)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(20)
    turtle.end_fill()
    turtle.pu()
    turtle.goto(-125, 5)
    turtle.pd()
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(15)
    turtle.end_fill()
    #8
    turtle.pu()
    turtle.goto(-110, 105)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(20)
    turtle.end_fill()
    turtle.pu()
    turtle.goto(-125, 125)
    turtle.pd()
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(15)
    turtle.end_fill()

def f1():
    turtle.color("black")
    turtle.pensize(6)
    turtle.pu()
    turtle.goto(-50, 158)
    turtle.pd()
    turtle.forward(100)
    turtle.rt(120)
    turtle.forward(100)
    turtle.rt(120)
    turtle.forward(100)
    turtle.rt(120)
    #
    turtle.pensize(1)
    turtle.pu()
    turtle.goto(-35, 150)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.forward(70)
    turtle.rt(120)
    turtle.forward(70)
    turtle.rt(120)
    turtle.forward(70)
    turtle.rt(120)
    turtle.end_fill()
    #
    turtle.pensize(7)
    turtle.pu()
    turtle.goto(-42, 154)
    turtle.pd()
    turtle.pencolor("white")
    turtle.forward(84)
    turtle.rt(120)
    turtle.forward(84)
    turtle.rt(120)
    turtle.forward(84)
    turtle.rt(120)
    #
    turtle.pensize(1)
    turtle.pu()
    turtle.goto(-42, 154)
    turtle.pd()
    turtle.pencolor("black")
    turtle.forward(84)
    turtle.rt(120)
    turtle.forward(84)
    turtle.rt(120)
    turtle.forward(84)
    turtle.rt(120)

def f2():
    turtle.pensize(4)
    turtle.pu()
    turtle.goto(-150, 70)
    turtle.pd()
    turtle.pencolor("black")
    turtle.forward(300)
    turtle.rt(120)
    turtle.forward(300)
    turtle.rt(120)
    turtle.forward(300)
    turtle.rt(120)
    #
    turtle.pu()
    turtle.goto(-120, 53)
    turtle.pd()
    turtle.forward(240)
    turtle.rt(120)
    turtle.forward(240)
    turtle.rt(120)
    turtle.forward(240)
    turtle.rt(120)
    #
    turtle.pensize(13)
    turtle.pu()
    turtle.goto(-135, 62)
    turtle.pd()
    turtle.pencolor("white")
    turtle.forward(270)
    turtle.rt(120)
    turtle.forward(270)
    turtle.rt(120)
    turtle.forward(270)
    turtle.rt(120)
    #
    turtle.pensize(2)
    turtle.pu()
    turtle.goto(-135, 62)
    turtle.pd()
    turtle.pencolor("black")
    turtle.forward(270)
    turtle.rt(120)
    turtle.forward(270)
    turtle.rt(120)
    turtle.forward(270)
    turtle.rt(120)

def x(a, b):
    turtle.pensize(1)
    turtle.pu()
    turtle.goto(a, b)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    for i in range(52):
        turtle.forward(100)
        turtle.left(175)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.right(2)
    turtle.end_fill()

def fs1():
    turtle.pu()
    turtle.home()
    turtle.goto(-25, 110)
    turtle.pd()
    turtle.pensize(1)
    turtle.rt(180)
    turtle.circle(47, 90)
    turtle.rt(90)
    turtle.circle(3, 180)
    turtle.pensize(2)
    turtle.rt(90)
    turtle.forward(53)
    turtle.pensize(1)
    turtle.circle(-7, 90)
    turtle.rt(60)
    turtle.circle(-20, 45)
    turtle.pensize(2)
    turtle.rt(120)
    turtle.circle(-17, 45)
    turtle.rt(180)
    turtle.circle(17, 45)
    turtle.rt(30)
    turtle.circle(-17, 45)
    turtle.rt(330)
    turtle.forward(40)
    turtle.circle(-53, 90)
    turtle.forward(10)
    turtle.rt(90)
    turtle.forward(70)
    turtle.rt(300)
    turtle.circle(-20, 45)
    turtle.rt(15)
    turtle.forward(37)
    turtle.pensize(1)
    turtle.rt(90)
    turtle.circle(-3, 90)
    turtle.forward(13)
    turtle.rt(180)
    turtle.forward(13)
    turtle.pensize(2)
    turtle.rt(30)
    turtle.circle(53, 45)
    turtle.circle(7, 135)
    turtle.rt(10)
    turtle.forward(4)
    turtle.pu()
    turtle.home()
    turtle.goto(-18, 48)
    turtle.pd()
    turtle.pensize(1)
    turtle.rt(205)
    turtle.circle(52, 65)
    turtle.sety(10)
    turtle.pensize(2)
    turtle.rt(300)
    turtle.circle(20, 120)
    turtle.rt(25)
    turtle.circle(55, 40)
    turtle.rt(300)
    turtle.circle(-3, 90)
    turtle.pensize(1)
    turtle.rt(280)
    turtle.circle(30, 45)
    turtle.rt(348)
    turtle.circle(50, 50)
    turtle.rt(340)
    turtle.circle(15, 50)
    turtle.rt(60)
    turtle.circle(-6, 60)
    turtle.rt(180)
    turtle.circle(6, 60)
    turtle.rt(150)
    turtle.circle(20, 130)

def fs2():
    turtle.pu()
    turtle.home()
    turtle.goto(25, 110)
    turtle.pd()
    turtle.pensize(1)
    turtle.rt(0)
    turtle.circle(-47, 90)
    turtle.rt(270)
    turtle.circle(-3, 180)
    turtle.pensize(2)
    turtle.rt(270)
    turtle.forward(53)
    turtle.pensize(1)
    turtle.circle(7, 90)
    turtle.rt(300)
    turtle.circle(20, 45)
    turtle.pensize(2)
    turtle.rt(240)
    turtle.circle(17, 45)
    turtle.rt(180)
    turtle.circle(-17, 45)
    turtle.rt(330)
    turtle.circle(17, 45)
    turtle.rt(30)
    turtle.forward(40)
    turtle.circle(53, 90)
    turtle.forward(10)
    turtle.rt(270)
    turtle.forward(70)
    turtle.rt(60)
    turtle.circle(20, 45)
    turtle.rt(345)
    turtle.forward(37)
    turtle.pensize(1)
    turtle.rt(270)
    turtle.circle(3, 90)
    turtle.forward(13)
    turtle.rt(180)
    turtle.forward(13)
    turtle.pensize(2)
    turtle.rt(330)
    turtle.circle(-53, 45)
    turtle.circle(-7, 135)
    turtle.rt(350)
    turtle.forward(4)
    turtle.pu()
    turtle.home()
    turtle.goto(17, 48)
    turtle.pd()
    turtle.pensize(1)
    turtle.rt(335)
    turtle.circle(-52, 65)
    turtle.sety(10)
    turtle.pensize(2)
    turtle.rt(60)
    turtle.circle(-20, 120)
    turtle.rt(335)
    turtle.circle(-55, 40)
    turtle.rt(60)
    turtle.circle(3, 90)
    turtle.pensize(1)
    turtle.rt(80)
    turtle.circle(-30, 45)
    turtle.rt(12)
    turtle.circle(-50, 50)
    turtle.rt(20)
    turtle.circle(-15, 50)
    turtle.rt(300)
    turtle.circle(6, 60)
    turtle.rt(180)
    turtle.circle(-6, 60)
    turtle.rt(210)
    turtle.circle(-20, 130)

def fs3():
    turtle.pu()
    turtle.home()
    turtle.goto(-75, 0)
    turtle.pd()
    turtle.pensize(2)
    turtle.rt(110)
    turtle.circle(25, 45)
    turtle.rt(320)
    turtle.circle(30, 45)
    turtle.pensize(1)
    turtle.rt(20)
    turtle.circle(25, 45)
    turtle.rt(20)
    turtle.circle(-10, 45)
    turtle.rt(340)
    turtle.circle(10, 45)
    turtle.rt(335)
    turtle.forward(20)
    turtle.rt(180)
    turtle.forward(20)
    turtle.rt(0)
    turtle.circle(45, 45)
    turtle.rt(355)
    turtle.circle(10, 120)

def fs4():
    turtle.pu()
    turtle.home()
    turtle.goto(75, 0)
    turtle.pd()
    turtle.pensize(2)
    turtle.rt(70)
    turtle.circle(-25, 45)
    turtle.rt(40)
    turtle.circle(-30, 45)
    turtle.pensize(1)
    turtle.rt(340)
    turtle.circle(-25, 45)
    turtle.rt(340)
    turtle.circle(10, 45)
    turtle.rt(20)
    turtle.circle(-10, 45)
    turtle.rt(25)
    turtle.forward(20)
    turtle.rt(180)
    turtle.forward(20)
    turtle.rt(0)
    turtle.circle(-47, 45)
    turtle.rt(19)
    turtle.circle(-10, 120)

def fs5():
    turtle.pu()
    turtle.home()
    turtle.goto(-40, -16)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.rt(55)
    turtle.circle(7, 135)
    turtle.rt(305)
    turtle.circle(7, 135)
    turtle.end_fill()

def fs6():
    turtle.pu()
    turtle.home()
    turtle.goto(26, -13)
    turtle.pd()
    turtle.color("black")
    turtle.begin_fill()
    turtle.rt(305)
    turtle.circle(-7, 135)
    turtle.rt(55)
    turtle.circle(-7, 135)
    turtle.end_fill()

def fs7():
    turtle.pensize(2)
    turtle.pu()
    turtle.home()
    turtle.goto(-15, -18)
    turtle.pd()
    turtle.rt(70)
    turtle.forward(25)
    turtle.rt(220)
    turtle.forward(20)
    turtle.rt(140)
    turtle.forward(20)
    turtle.rt(220)
    turtle.forward(25)
    turtle.pensize(1)
    turtle.pu()
    turtle.home()
    turtle.goto(-15, -27)
    turtle.pd()
    turtle.rt(70)
    turtle.forward(18)
    turtle.pu()
    turtle.home()
    turtle.goto(-3, -40)
    turtle.pd()
    turtle.rt(290)
    turtle.forward(8)
    turtle.rt(135)
    turtle.forward(8)
    turtle.pu()
    turtle.home()
    turtle.goto(11, -40)
    turtle.pd()
    turtle.rt(290)
    turtle.forward(18)

def fs8():
    turtle.pensize(2)
    turtle.pu()
    turtle.home()
    turtle.goto(-70, -20)
    turtle.pd()
    turtle.rt(70)
    turtle.circle(15, 100)
    turtle.circle(-15, 100)
    turtle.rt(330)
    turtle.circle(-50, 55)

def fs9():
    turtle.pensize(2)
    turtle.pu()
    turtle.home()
    turtle.goto(70, -20)
    turtle.pd()
    turtle.rt(110)
    turtle.circle(-15, 100)
    turtle.circle(15, 100)
    turtle.rt(30)
    turtle.circle(50, 55)
    turtle.pu()
    turtle.sety(500)

#
circ1()
cua()
lines()
circ2()
circ3()
f1()
f2()
fs1()
fs2()
fs3()
fs4()
fs5()
fs6()
fs7()
fs8()
fs9()
x(220, 0)
x(-220, 0)

#
turtle.done()
